### ISSUE TITLE
Add Pushover recipient class with device specification

### ISSUE THREAD

**Issue by christianWillingBgpEmedia** [laravel-notification-channels/pushover#11]
Hi, is there a way to send the message to only one device ?

**Comment by casperboone** [comment]
At the moment there is no way to do this unfortunately.

This would maybe add to much complexity, since you would have to return some kind of PushoverRecipient object from the `routeForPushover` method of your notifiable (user). I have never seen the use case of sending a message to a specific device, but understand that you do have one. I will think about a good way to implement this capability and update you here.

**Comment by christianWilling** [comment]
Thank you
